### ISSUE TITLE
Discussion start

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#1]
Dear all,

I think we should start our discussion with the very good discussion paper.

I have made some comments to the [paper](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Discussion%20Paper%20on%20data-service%20linking%20v0.5_Austrian_Comments.docx) - feel free to comment the comments, but open a new issue per theme.

Best regards Erik

**Comment by dartasensi** [comment]
@oberseri thanks for opening this space with a first discussion. 👍 

I would thank you for your in-depth analysis on the discussion paper: I had a look at your comments, I mostly agree on them, and there are quite some interesting discussion points (eg. on the table with the proposed changes on INSPIRE elements).
We are evaluating an effective way to discuss your points (for instance, options are to share the document on WordOnline/OneDrive, or a markdown conversion of the docx, in order to use citations here in this GitHub space).

May I ask you a small clarification on the term `ODPSI-DIR`: are you referring to the Open Data (former PSI) Directive?

**Comment by oberseri** [comment]
Thank you Davide! and yes I have meant the Open Data Directive

**Comment by AntoRot** [comment]
The comments were taken into account in the initial discussions and proposals of this work.
The issue can be closed.
