### ISSUE TITLE
protocol label

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/gp-data-service-linking-simplification#11]
In the consolidated proposal presented by JRC, i see a deviation in the description of the protocol element.   The URI provided in https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue should be used in gmx:Anchor xlink:href  and the label can contain the national representation of that value, as discussed/ agreed earlier.

**Comment by dartasensi** [comment]
Dear @idevisser 

thanks for indicating this, but I don't see the deviation you're mentioning. Could you express it further?

We agree that the `protocol` element should use the already [available codelist](https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue). This codelist was created from the initial efforts and meetings on Simplification, around 2019. For instance, in the discussion paper, it presents a more complex codelist but it was discarded and we proposed the current one.

The consolidated proposal is trying to simplify the long text expressed by the current codelist (ie. `label`).
If we decide to keep the support for `gco:CharacterString` , in order to be parsed it should match exactly the label declared in the registry.
If we decide to follow the recommended practice from the MD TG v2.0 (ie. to use `gmx:Anchor` for expressing codelist values with URI, instead of the simpler `gco:CharacterString`), I agree with you that the `xlink:href` has priority over the textual content and so it can contain the exact label in the language of the metadata (ie. "_the national representation of that value_"), but also a different but more human readable text.

**Comment by idevisser** [comment]
The use of a gmx:Anchor for expressing the codelist value with an URI is preferred, because this can be used in combination with the national values  in the label. The URI  can support easy filtering. Textual values are sensitive to errors. Support of Characterstring  should not be allowed  for simpler data service linking in the protocol element.

**Comment by jsaligoe** [comment]
Dear @dartasensi and @idevisser, 
we appreciate this discussion of the value of using URIs (gmx:Anchor xlink:href) as the preferred method and we follow this approach on several elements per the existing Metadata TG. Yet for the proposed approach 'protocol' and 'application profiles' we suggest there should be enough room in validation tests to also support using gco:CharacterString matching exactly the label for the code list values declared in the registry.

Justification for a more flexible approach include:
- Standard web applications often must support a wider variety of protocol than those declared in the INSPIRE domain list
- Using use a codelist value matching exactly the central INSPIRE Registry is easily accomplished using CharacterString
- Allowing a more flexible approach (either URI or CharacterString) is proven to be implementable and would ensure support of the widest range of web applications available today, thus would immediately enable increased levels of accessibility of INSPIRE data sets through view and download services

Supporting a more flexible approach that strongly recommends URI rather than making it mandatory would be consistent with the Good Practice objective of simplification of data-service linking that is proven to be implementable by de facto standard web applications.

respectfully,

**Comment by idevisser** [comment]
the  proposed flexible approach is elaborated in the requirements and recommendations in the good practice document
