### ISSUE TITLE
Referencing a specific layer/feature type in capabilities

### ISSUE THREAD

**Issue by pvgenuchten** [INSPIRE-MIF/gp-data-service-linking-simplification#14]
I haven't seen this discussion in any of the threads, please correct me if i missed it. 

In GeoNetwork (and adopted by some national profiles on iso19139) we have a convention to reference the layer/featuretype name (from service capabilities) in the gmd:name element of gmd:online. In that way being able to reference to the layer within the capabilities described by the current metadata record.

I am aware INSPIRE 'solves' this challenge by using ows:identifier (and/or ows:metadataUrl), but still the reference by name approach is quite common and adds an additional mechanism in case ows:identifier is not populated.

Let me list some related topics here for consideration:

- In https://metadata101.github.io/schemas/fgp/hnap/HNAP.html a suggestion is made to add the relevant layer as additional parameter to the capabilities url
- In the OGC API Records we're trying to capture this challenge as part of the standard, discussion is at https://github.com/opengeospatial/ogcapi-records/issues/95. OGC API seems to move to a templated approach, e.g. https://example.com/wms?request=getMap&layer=forest&bbox={bounds}&crs={srs}&width={width}&height={height}

**Comment by AntoRot** [comment]
Dear @pvgenuchten 

in the issue #13 I submitted, I proposed to use the `gmd:name` element in the metadata record to be encoded with the layer/featuretype name included in the service capabilities.

The proposal in the issue is specifically for WMS (i.e. the `gmd:name` element in the metadata record to be encoded with the value of the layer property `<Name>`) but to be extended to WFS.

So, I agree ;)

**Comment by AntoRot** [comment]
Below the similar proposal made in the issue #13, copied and pasted here for discussion as suggested by @dartasensi 

I think that the GetCapabilities request should be used as value of the linkage element, as pointed above.
Alternatively, another proposal for WMS could be as follows:
- if the network service provides view access only to one data set and the layer has a `<Name>` property, then the resource locator may be the GetMap request  with that Name as the value of LAYERS argument, otherwise, if no `<Name>` property is included, the GetCapabilities request;
- if the network service provides view access to several data sets and each layer has a `<Name>` property, then:
  -  either the resource locator may be the GetMap request with that Name corresponding to the data set described by the metadata record as the value of LAYERS argument
  - or the resource locator may be the GetCapabilities request with the `gmd:name` element in the metadata record encoded with the value of the layer property `<Name>`;
- if the network service provides view access to several data sets and no layer has a `<Name>` property, then the resource locator may be the GetCapabilities request.

A similar proposal could be defined for the other network services.

**Comment by MetaGIS** [comment]
I do not so keen using the name-element from the online-resource. It already has a defined usage in ISO 19115 and is often used as tootip information in GeoPortals to give information on what the Online link is about. 

We prefer using the design as implemented by North American Profile of metadata as described by Paul.  (https://metadata101.github.io/schemas/fgp/hnap/HNAP.html )
Eg http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway
or for multiple layers
http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway,main-railways


Using a GetMap request gives a direct result for users  but to define a GetMap request you must decide Spatial referenssystem, extent and size of image. Thoose values might be wrong for users and they need anyhow to learn how they can adjust the parameters  to get the requests they need. To show example of requests to a WMS-service we would prefer adding this as a browse-image URL to a live   WMS-service.

**Comment by LauraAlemany** [comment]
Hello, 

I agree with @MetaGIS. The name-element from the online-resource is often used as tootip information.

But the is something I am not suere I am understanding well. 
I don´t see any difference between the URL-examples you give. For me both URL have the same response as the GetCapabilities, don´t they?
 - [http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway](http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway)
 - [http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway,main-railways](http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities&layers=railway,main-railways)
 - [http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities](http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities)

Maybe I misunderstood something...

**Comment by fabiovin** [comment]
Dear @LauraAlemany,

as I understood it, adding the "layers" parameter is only to indicate the respective layer in the WMS and, as you pointed, has no effect on the response of the service.

We cannot probably force the use of the `gmd:name` element for reporting the name of the related WMS layer. It may be a recommendation.

A more robust reference should be made by the use of the "_Unique Resource Identifier_" metadata element, mapped on the `wms:Identifier` element of the `<wms:Layer>`. But it seems that its implementation is not so easy/clear.

**Comment by AntoRot** [comment]
After the initial discussion, the `gmd:name` element is no more considered in the final proposal of the good practice. 
However, based on the metadata TG  Recommendation 1.9  the element is recommended to be used to give additional information about the provided URL link and it could also be used to reference the layer/featuretype name.
Consequently this issue can be closed.
