### ISSUE TITLE
Comments on the section 8.2

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#30]
I think that the requirements in the section 8.2. are redundant as they are already defined in the INSPIRE MD TG and in INSPIRE NS - View / Download Service TG.
In addition, although service metadata is indicated as optional in the section 7.2, it is ultimately mandatory because:
- if Member State decides to follow the scenario 1 then a service metadata record is required to be referenced through the `<inspire_common:MetadataURL>` element within the INSPIRE ExtendedCapabilities section;
- if Member State decides to follow the scenario 2 then all the service metadata elements shall be documented in the ExtendedCapabilities section.

This because it was decided not to address the issue of removing the ExtendedCapabilities, that makes the simplification action incomplete in my opinion.

**Comment by jescriu** [comment]
Dear @AntoRot,

I am providing here an update to the current situation. 

At the moment we are working on finishing Action 2.3.2 on Data-Service Linking Simplification, including a proposal for removing the Extended Capabilities - which will probably become an additional scenario (let's say scenario 3).

As per my understanding [section 7.2](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#72-resources-) graphic indicates that service metadata is optional, but in the context of the current good practice proposal.

This means that the TGs should be amended in order to make service metadata conditional, depending on the scenario chosen  (scenarios 1, scenario 2 or the potential scenario 3).

Let me know if this OK with you.

In the meantime, I am closing this issue, since you marked it as duplicate in #45.

Jordi

**Comment by AntoRot** [comment]
I agree in closing this issue!
