### ISSUE TITLE
Coupled resource implementation is not compliant

### ISSUE THREAD

**Issue by MarieLambois** [INSPIRE-MIF/gp-data-service-linking-simplification#38]
ISO requirement for the operatesOn element is the following:
![image](https://user-images.githubusercontent.com/12797943/142900859-879bc795-148f-4283-9464-eaf5d0117b09.png)
Thus the link should point to a MD_DataIdentification XML element. 
However in the current proposal the link will point to the MD_Metadata element.

Suggestion: Addition of #MD_DataIdentification at the end of the URL would make the proposal compliant with ISO.

**Comment by oberseri** [comment]
Austria suggests in its national md-guidline to use a http-URI as INSPIRE-UniqueRessourceIdentifier. This URI is redirected to the md-record at the national geoportal (automatically by the responsible authority).

Using this URI as CR _... identifies, where relevant, the target spatial dataset(s) of the service through their unique ressource identifier ..._(unfortunately not iso complient ...).
We would welcome beeing able to keep our approach.

**Comment by jescriu** [comment]
###2022-02-25 Discussion:
Based on the discussion hold in the 2nd meeting for the 'Remapping of the extended capabilities', corresponding to Part B of the work of MIWP Sub-group on Action 2.3.2 'Simplification of Data and Service Linking', it was agreed to relax the implementation of the Coupled Resource by making the linkage to the #MD_DataIdentification section of the metadata an optional feature (i.e. pointing to the URL of the metadata, with or without the additional #MD_DataIdentification pointer)
(See specific agreement in the [minutes of the meeting](TG Requirement 3.6 of the [INSPIRE Technical Guidelines on Metadata v2.1.0](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.1/metadata/metadata-iso19139/metadata-iso19139.adoc#4124-linking-to-provided-data-sets-using-coupled-resource) (TG MD)))

#### Rationale
Although ISO 19119:2005 requires that the target of the operatesOn element (Coupled Resource) is the #MD_DataIdentification class of the linked dataset metadata, due to the different existing metadata implementations, it was agreed to allow a more simple implementation the Coupled Resource linkage. 

As a result, TG Requirement 3.6 of the [INSPIRE Technical Guidelines on Metadata v2.1.0](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.1/metadata/metadata-iso19139/metadata-iso19139.adoc#4124-linking-to-provided-data-sets-using-coupled-resource) (TG MD) needs to be changed.

#### Changes to the current INSPIRE framework
TBD

**Comment by MarieLambois** [comment]
The wording proposed by @jescriu makes sense to me. Maybe an example with an URI (as mentionned by @oberseri) could be added as well ?

**Comment by oberseri** [comment]
A working Austrian URI example could be: https://data.inspire.gv.at/9db8a0c3-e92a-4df4-9d55-8210e326a7ed
