### ISSUE TITLE
Part B - Remapping of Extended Capabilities - About temporal reference

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#40]
My proposal:
- if the network service serves only one layer/feature type, then the date of publication of the corresponding data set (documented in the data set metadata) could be considered as the temporal reference of the service; 
- if the network service serves more layers/feature types, then the temporal reference of the service could correspond to the earliest publication date among those ones documented in the corresponding data sets metadata;
- if the temporal reference of the corresponding data sets is documented through temporal extents, then the temporal extent of the network service could be composed with a start date corresponding to the earliest start date of the data sets and a end date corresponding with the most recent end date of the data sets.

Maybe this could imply an additional requirement in the Good Practice guidelines about the obligation of a date of publication.

**Comment by MarieLambois** [comment]
I think this kind of method, taking dates from the data, is relevant. At the end, the user does not really care about when the service was started but cares about when the data was published or updated. In order to avoid adding constraints to the dataset metadata date, maybe taking the latest of all dates is OK?

**Comment by AntoRot** [comment]
About the metadata date I agree that the latest date should be taken into account, as expressed in the issue #42.

**Comment by jescriu** [comment]
Dear @AntoRot,

Thank you for your proposal on the Temporal reference.

TG Requirement C.11 from the current [Metadata technical guidelines](https://inspire.ec.europa.eu/file/1705/download?token=iSTwpRWd) requires the provision of at least one temporal reference using either the date of publication, the date of last revision or the date of creation of the resource. At the same time, TG Requirement C.12 and TG Requirement C.13, are limiting the provision of date of creation and date of revision to only one instance, respectively.

In line with the comment from @MarieLambois, I also think the most relevant date types for the user are those related to the data, i.e. the date of last revision or the date of publication of the data, rather than the date of creation.

It is not clear to me if in you first post you are explicitly proposing to use only the dates of publication, rather than the other possible types of dates (data of last revision, date of creation) - Could you please clarify this aspect? And if this is the case, provide a justification for choosing it and not the others?

The approach of taking the latest date available makes sense to me.

**Comment by idevisser** [comment]
Think we should not make it too complicated and can be pragmatic; taking the last date of the dataset(s)

**Comment by jescriu** [comment]
I agree. It is a matter of clarifying the possible concepts associated to the last date - i.e. what it represents.

**Comment by AntoRot** [comment]
Dear @jescriu,

I confirm that my proposal is to consider only the publication date as reference date for the service based on the following assumptions:

- as the reference date of the service in the new approach will be expressed in the data set metadata record, we should agree on what date refers to data set and what one to the service. I think that the creation and revision dates are more relevant for data set. In other words, if a data provider creates a data set, it is not certain that data set will be made available through a service in the same date and in case of revision, this event is to refer to data set and not service because the service was implemented before the data set was revised;
- the publication date of a dataset could mean both when the data set is made available and when a service (whose endpoint is given in the same metadata record) was released to make that data set available. For this reason I proposed to consider the earliest publication date (in case more layers/features are served) as the service exists since that date.

**Comment by idevisser** [comment]
I come back to my earlier comment in this issue.
In many cases, when managing the metadata only in the capabilities (no longer in a separate XML), the metadata date will correspond to the creation/update/publication date of the service.
Issues #42  and issue #40  therefore require the same approach and should lead to the same mapping.

I currently see two options, for both the temporal reference and the metadata date of the service;
option 1: If it is not possible to include the date in the capabilities of a service, in this case the publication date in the dataset metadata could also be the publication date of the service and its metadata, as proposed and argued by @AntoRot 
option 2: If it is possible to include a date in the capabilities of a service; the updateSequence element for WMS/WFS and for ATOM the atom:updated element, as seems possible in @heidivanparys  explanation on issue #42 , this element could be the publication date of the service and its metadata. 

One thing to keep in mind is that the service is often managed by a different person/organizational unit/organization than the dataset itself. An update of the data does not immediately mean an update of a service. Option 2 gives the best picture in that case.

**Comment by MarieLambois** [comment]
I think we are here talking about the "simple" use case where the service provider is closer enouth to the data provider and they can synchronize. In more complicated ones we would keep using the service metadata.

**Comment by idevisser** [comment]
2022-02-25 Discussion:
Based on the previous discussion, it was agreed to adopt a solution based on the following prioritised criteria:
A. if an atom:updated date value (in case of ATOM) or an UPDATESEQUENCE date value is present, take this value as Temporal reference of the service (Only in the case an standardised date format might be used and retrieved - checks required with ISO / OGC).
B. Failing A, check the dataset metadata for the existence of the following dates:
B1. If a date of type 'publication' is present, take this value as Temporal reference.
B2. Failing B1: If a date of type 'revision' is present, take this value as Temporal reference.
B3. Failing B2: Otherwise, take the date of type 'creation' as value of the Temporal reference.
The check with ISO / OGC about the possibility to use a standardised date format for UPDATESEQUENCE confirms that a standardized date format, a string that represents a timestamp in ISO 8601:2004 format should be used. See https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/42#issuecomment-1075603304

### Final proposal:
Proposed mapping and rationale

Temporal reference1 will be mapped to


- The optional attribute ‘updatesequence’ in case of a OGC:WMS or OGC:WFS
- The mandatory ‘updated’ in case of an Atom

If this attribute is present in the service metadata. This means that the last update of the service metadata is assumed equal to the update date of the service.
The extended ISO 8601:2000 format, ccyy-mm-ddThh:mm:ss.sssZ whereby the precision may be reduced by omitting least-significant digits, e.g. 2022-01-26 or 2022-01-26T09:30Z, must be used.
If this optional attribute is not present, the Metadata Date is mapped to the Temporal reference1 of the dataset metadata:

If a date of type 'publication' is present, take this value as Metadata Date.
If a date of type 'revision' is present, take this value as Metadata Date.
Otherwise, take the date of type 'creation' as value of the Metadata Date.
This means that the last update of the service metadata is assumed the same as the publication or revision date of the data set.
The same mapping is also used to derive the Temporal reference of the service.


1 In a ISO/TS 19139 metadata record, Temporal reference is mapped to
MD_Metadata.identificationInfo > MD_DataIdentification.citation > CI_Citation.date > CI_Date.date element, see also [TG metadata].

The reasoning behind is that:
• The metadata in the capabilities is part of the service, so the update date of the metadata and the service are the same.
• Metadata date is INSPIRE/ISO terminology, whereas the term used in the relevant OGC specifications seems to be “update”.
• It should be clear that this section is about mapping the INSPIRE metadata elements to the capabilities of services, so moving the mapping to ISO 19139 to a footnote.
• The update attribute is optional in WXS, a fallback scenario is needed if this attribute is not present.
• In the case of deriving the Metadata date of the service, from the dataset metadata, a strong connection between the administrator of the dataset metadata and the administrator of the service is needed.

Detailed mapping description

For WMS 1.3 ([XML schema](http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd)):

```
<element name="WMS_Capabilities">
<annotation>
   <documentation>
        A WMS_Capabilities document is returned in response to a
        GetCapabilities request made on a WMS.
   </documentation>
</annotation>
<complexType>
   <sequence>
      <element ref="wms:Service"/>
      <element ref="wms:Capability"/>
   </sequence>
   <attribute name="version" type="string" fixed="1.3.0"/>
   <attribute name="updateSequence" type="string"/>
</complexType>
	</element>
```

So it would look like this in a GetCapabilities response:

```
<WMS_Capabilities
  xmlns="http://www.opengis.net/wms"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  version="1.3.0"
  updatesequence="2022-01-26"
  xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd>
  <!-- ... -->
</WMS_Capabilities>
```

For WFS 2.0, that uses the [OWS 1.1 schemas](http://www.opengis.net/ows/1.1)

```
<complexType name="CapabilitiesBaseType">
   <annotation>
      <documentation>XML encoded GetCapabilities operation response.
      </documentation>
   </annotation>
   <sequence>
      <element ref="ows:ServiceIdentification" minOccurs="0"/>
      <element ref="ows:ServiceProvider" minOccurs="0"/>
      <element ref="ows:OperationsMetadata" minOccurs="0"/>
   </sequence>
   <attribute name="version" type="ows:VersionType" use="required"/>
   <attribute name="updateSequence" type="ows:UpdateSequenceType"
use="optional">
      <annotation>
         <documentation>Service metadata document version, having
values that are "increased" whenever any change is made in service
metadata document. Values are selected by each server, and are always
opaque to clients. When not supported by server, server shall not
return this attribute. </documentation>
         </annotation>
    </attribute>
</complexType>
```

So it would look like this in a GetCapabilities response:

```
<WFS_Capabilities xmlns="http://www.opengis.net/wfs/2.0" 
    xmlns:ows="http://www.opengis.net/ows/1.1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" 
    xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd"
    updateSequence="2022-01-26">
    <ows:ServiceIdentification>

```

For An ATOM feed

```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0" xml:lang="nl">
<updated>2022-01-26T00:00:00Z</updated>
```

**Comment by idevisser** [comment]
I checked https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md#34-temporal-reference- 

the sentences "For a WXS, this means that the last update of the service metadata is assumed to be the same as the publication, revision or creation date of the data set. For Atom, this means that the last update of the service metadata is assumed equal to the update date of the service." is not correct. 

the first part, can be on this place with a small change "For a WXS **where the optional updateSequence is not present**, this means that the last update of the service metadata is assumed to be the same as the publication, revision or creation date of the data set."

The second part should be placed below

- The optional updateSequence attribute in case of a WXS if in this attribute a timestamp value is present;
- The mandatory <updated> in case of an Atom

and with a small change 
" this means that the last update of the service metadata is assumed equal to the update date of the service."

(this is not ATOM specific)

**Comment by idevisser** [comment]
in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/64 this is updated

**Comment by idevisser** [comment]
https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/61 done in 

https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/66

**Comment by jescriu** [comment]
This issue has been taken into account the current specification.
