### ISSUE TITLE
Part B - Remapping of Extended Capabilities - About Metadata date

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/gp-data-service-linking-simplification#42]
As some information about the network service will be moved to the data set metadata with the simplification approach, then it is reasonable to assume that the metadata date for the service is the one provided in the data set metadata.
In case the network service serves more layers/feature types, the metadata date could correspond to the most recent metadata date among those ones documented in the corresponding data sets metadata as the TG Requirement C.7 requires that the latest update date of the metadata description shall be given.

**Comment by MarieLambois** [comment]
I agree.

**Comment by idevisser** [comment]
This proposal supports not the use case, that the services are managed by other organisations...It would be nice if we can find a solution more in line with that use case, like the MetadataPointOfContact..., because the data itself can be updated and the service not (yet).
Is UpdateSequence (WMS) an fitting alternative?

**Comment by jescriu** [comment]
As per ISO 19128:2005 Section 7.2.3.5, the UpdateSequence value is optional: 
> _The server may include an UpdateSequence value in its service metadata. If present, this value should be increased when changes are made to the Capabilities (e.g. when new maps are added to the service)_.

**Comment by AntoRot** [comment]
We are referring to the metadata date and not to the revision date of data set or service.

**Comment by jescriu** [comment]
I think it depends on the criteria that it is finally agreed by the sub-group.

Based on my understanding of your inputs:

* **Criteria 1: by @AntoRot**
Metadata date of the service IS CONSIDERED EQUAL TO the metadata date of the dataset.

> As some information about the network service will be moved to the data set metadata with the simplification approach, then it is reasonable to assume that _the metadata date for the service is the one provided in the data set metadata_.

NOTE: With metadata date we are referring to 'MD_Metadata > dateStamp'. 

* **Criteria 2: by @idevisser**
Service metadata IS CONSIDERED EQUAL TO Service Capabilities document
and therefore
Metadata date of the service IS CONSIDERED EQUAL TO date of the Service Capabilities document.

Let me know if I understood both of you correctly, and if so which criteria are you supporting.

**Comment by jescriu** [comment]
>  NOTE: This criteria would support the use case when the services are managed by other organisations different from the data provider.

For coherence with the consensus approach taken on [Issue #41](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/41), we should also cover this use case here.

**Comment by LauraAlemany** [comment]
As I pointed out in the [Issue #41](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/41), in Spain the services are managed by different organizations from the data provider in many cases, so we prefer Criteria 2 by @idevisser.

For us, the metadata date in the extended capabilities refers to the metadata date of the resource, i.e the service, not the metadata date of the data set that the service provides. For instance, lets say we have a WMS with 2 layers and we change the abstract in the dataset metadata file associated to one of the layers, that doesn’t implies that the abstract of the GetCapabilities is updated. 

We agree on the proposal of using the UPDATESEQUENCE for WMS, but I am not sure what can we use for WFS and ATOM...

**Comment by heidivanparys** [comment]
From http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd

```xml
<element name="WMS_Capabilities">
		<annotation>
			<documentation>
        A WMS_Capabilities document is returned in response to a
        GetCapabilities request made on a WMS.
      </documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="wms:Service"/>
				<element ref="wms:Capability"/>
			</sequence>
			<attribute name="version" type="string" fixed="1.3.0"/>
			<attribute name="updateSequence" type="string"/>
		</complexType>
	</element>
```

So it would look like this in a `GetCapabilities` response:

```xml
<WMS_Capabilities
  xmlns="http://www.opengis.net/wms"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  version="1.3.0"
  updatesequence="20220126"
  xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd>
  <!-- ... -->
</WMS_Capabilities>
```

MapServer seems to support this, see https://www.kralidis.ca/blog/2008/02/12/mapserver-and-wxs-updatesequence/.

For **WFS**, it is a similar `updateSequence` attribute, see the [OGC Web Services Common Specification, OGC 06-121r3](https://portal.ogc.org/files/?artifact_id=20040) and screenshots below. Note that in that specification – as opposed to in the [WMS specification](http://portal.opengeospatial.org/files/?artifact_id=14416) – it is stated explicitly that a server implementation does not have to support this functionality, it is optional functionality.

![image](https://user-images.githubusercontent.com/11427611/151195200-42326236-b548-4d91-a89b-283a02cef5d7.png)

![image](https://user-images.githubusercontent.com/11427611/151195229-2564a359-86e5-44a4-80c1-0fd1c88ffbb4.png)

![image](https://user-images.githubusercontent.com/11427611/151195124-d33a42c4-7767-44e3-9feb-afbd70e2adb4.png)

For **Atom**, this is already specified in the [TG download](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services), the [atom:updated element](https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.15) is used:

![image](https://user-images.githubusercontent.com/11427611/151195547-aad0c0cb-ff80-4fb4-9be1-5c48f84ae194.png)

![image](https://user-images.githubusercontent.com/11427611/151195583-596cd988-410d-4749-92fc-d6c9bbc64761.png)

**Comment by heidivanparys** [comment]
Regarding the action on me in [the meeting minutes of the 25th of February](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/meetings/2022-02-25/MIWP%20Sub-group%202.3.2%20Simplification%20Part%20B%202022-02-25.md), "check with ISO / OGC about the possibility to use a standardised date format for `UPDATESEQUENCE`": I reread the relevant parts of the standards and found the following:

In [WMS 1.3](http://portal.opengeospatial.org/files/?artifact_id=14416) (highlighting is mine):

> 7.2.3.5 UPDATESEQUENCE
> The optional UPDATESEQUENCE parameter is for maintaining cache consistency. Its value can be either an integer, or a **string that represents a timestamp in ISO 8601:2004 format (see Annex D)**, or any other string. 

> Annex D
> (normative)
> Web Map Service profile of ISO 8601
> 
> […]
> 
> D.2.1 Basic syntax
> The basic time format uses ISO 8601:2000 “extended” format: up to 14 digits specifying century, year, month, day, hour, minute, and seconds, and optionally a decimal point followed by zero or more digits for fractional seconds, with non-numeric characters to separate each piece:
> `
> ccyy-mm-ddThh:mm:ss.sssZ`
> 
> The precision may be reduced by omitting least-significant digits […]

So the extended format, e.g. `2022-01-26` or `2022-01-26T09:30Z`, must be used instead of the basic format, e.g. `20220126` or `20220126T0930Z`, in WMS.

Regarding (highlighting is mine)

> 7.3.4 updateSequence parameter
> The optional updateSequence parameter may be used for maintaining the consistency of a client cache of the contents of a service metadata document. The parameter value may be an integer, **a timestamp in [ISO 8601:2000] format**, or any other number or string.

Here there is no reference to or description of the precise format to be used, extended or basic, as long as it is ISO 8601 compliant. So a client has to be able to handle both, I guess.

Note: for Atom the extended format has to be used, see https://datatracker.ietf.org/doc/html/rfc4287#section-3.3 and https://datatracker.ietf.org/doc/html/rfc3339.

**Comment by idevisser** [comment]
2022-02-25	Discussion:
Based on the previous discussion, it was agreed to adopt a solution based on the following prioritised criteria:
A. if an atom:updated date value (in case of ATOM) or an UPDATESEQUENCE date value is present, take this value as Metadata Date (Only in the case an standardised date format might be used and retrieved - checks required with ISO / OGC).
B. Failing A, check the dataset metadata for the existence of the following dates:
B1. If a date of type 'publication' is present, take this value as Metadata Date.
B2. Failing B1: If a date of type 'revision' is present, take this value as Metadata Date.
B3. Failing B2: Otherwise, take the date of type 'creation' as value of the Metadata Date.
The check with ISO / OGC about the possibility to use a standardised date format for UPDATESEQUENCE confirms that a standardized date format, a string that represents a timestamp in ISO 8601:2004 format should be used. See https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/42#issuecomment-1075603304

**### Final proposal:**
**Proposed mapping and rationale**

Metadata Date1 will be mapped to 
-	The optional attribute ‘updatesequence’ in case of a WXS or 
-	The mandatory ‘updated’ in case of an Atom 
if this attribute is present in the service metadata. This means that the last update of the  service metadata is assumed equal to the update date of the service. 
The extended  ISO 8601:2000 format, ccyy-mm-ddThh:mm:ss.sssZ whereby the precision may be reduced by omitting least-significant digits, e.g. 2022-01-26 or 2022-01-26T09:30Z, must be used.

Otherwise, if this optional attribute is not present, the Metadata Date is mapped to the Temporal reference2 of the dataset metadata: 
-	If a date of type 'publication' is present, take this value as Metadata Date.
-	If a date of type 'revision' is present, take this value as Metadata Date.
-	Otherwise, take the date of type 'creation' as value of the Metadata Date.

This means that the last update of the service metadata is assumed the same as the publication or revision date of the data set.
The same elements are also used to derive the Temporal reference of the service.

1 In a ISO/TS 19139 metadata record, Metadata Date is mapped to MD_metadata.dateStamp, see also [TG metadata].
2 In a ISO/TS 19139 metadata record, Temporal reference is mapped to
MD_Metadata.identificationInfo > MD_DataIdentification.citation > CI_Citation.date > CI_Date.date element.



The reasoning behind is that:
•	The metadata in the capabilities is part of the service, so the update date of the metadata and the service are the same. 
•	Metadata date is INSPIRE/ISO terminology, whereas the term used in the relevant OGC specifications seems to be “update”.
•	It should be clear that this section is about mapping the INSPIRE metadata elements to the capabilities of services, so moving the mapping to ISO 19139 to a footnote.
•	The update attribute is optional in WXS, a fallback scenario is needed if this attribute is not present.
•	In the case of deriving the Metadata date of the service, from the dataset metadata, a strong connection between the administrator of the dataset metadata and the administrator of the service is needed.


**Detailed mapping description**
<element name="WMS_Capabilities">
		<annotation>
			<documentation>
        A WMS_Capabilities document is returned in response to a
        GetCapabilities request made on a WMS.
      </documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="wms:Service"/>
				<element ref="wms:Capability"/>
			</sequence>
			<attribute name="version" type="string" fixed="1.3.0"/>
			<attribute name="updateSequence" type="string"/>
		</complexType>
	</element>

So it would look like this in a GetCapabilities response:
<WMS_Capabilities
  xmlns="http://www.opengis.net/wms"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  version="1.3.0"
  updatesequence="2022-01-26"
  xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd>
  
</WMS_Capabilities>

TODO ATOM

**Comment by idevisser** [comment]
In https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md#37-metadata-date-

the sentences "For a WXS, this means that the last update of the service metadata is assumed to be the same as the publication, revision or creation date of the data set. For Atom, this means that the last update of the service metadata is assumed equal to the update date of the service." is not correct.

in the first part, can be on this place with a small change "For a WXS where the optional updateSequence is not present, this means that the last update of the service metadata is assumed to be the same as the publication, revision or creation date of the data set."

The second part should be placed below

The optional updateSequence attribute in case of a WXS if in this attribute a timestamp value is present;
The mandatory in case of an Atom
and with a small change
" this means that the last update of the service metadata is assumed equal to the update date of the service."

(this is not ATOM specific)

**Comment by idevisser** [comment]
https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/61 done in 

https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/pull/66

**Comment by jescriu** [comment]
This issue has been taken into account the current specification.
