### ISSUE TITLE
coupled ressources

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#5]
The "coupled ressources" in the service-getCap (= MetadataURL) are extremely valuable - we should keep them in any way (especially when the service-md are removed)
If service-md are maintained, how to handle differences in the cr of the service-md and the MetadataURL of the service-getCap (e.g. in the validation or the data-service-linking)?

Erik

**Comment by idevisser** [comment]
We support to require to keep the link to the dataset metadata (MetadataURL) in the capabilities

**Comment by dartasensi** [comment]
@idevisser @oberseri I think that we, as JRC, also support this.

Going even further, in order to claim the "downloadable/viewable" aspect on that _simplified_ dataset, I still see the `metadataURL` element as mandatory. What's your opinion?

**Comment by MetaGIS** [comment]
I support the requirement to always keep MetadataURL for layers in WMs services but also for featuretypes in WFS and datasetentrys in a ATOM-feeds. 
As I understand it it is now not mandatory in WFS-service. It would be easier to handle same concept in WFS as we use in WMS-services. But maybe there some advantages to keep the spatialDatasetIdentitier that is not clear for me.

**Comment by LauraAlemany** [comment]
I agree with MetaGIS. I also support the requirement to keep MetadataURL for layers in WMS services, for featuretypes in WFS and dataset entrys in ATOM-feeds. 

Regarding the “_advantages to keep the spatialDatasetIdentitier_” I am not so sure.

I think it is important to have everything linked. If you go to the **dataset metadata** you can see in which services you can see that specific dataset looking at the element **<gmd:CI_OnlineResource>**. And if you visit the **URL of the service** you can access the dataset metadata through the element **MetadataURL**. I would keep these elements.

But **maybe there is no need to use the following md-elements** in the metadata dataset file:
```xml
<gmd:RS_Identifier>
           <gmd:code><gco:CharacterString>BDLJE</gco:CharacterString></gmd:code>
          <gmd:codeSpace><gco:CharacterString>IGN</gco:CharacterString></gmd:codeSpace>
</gmd:RS_Identifier>
```
to link with the **GetCapabilities** of the services that show that specific dataset using the following for a **WMS** (in each layer):
```xml
<Identifier authority="IGN">bdlje_limites_adm</Identifier>
```
or using the following for the **WFS**
```xml
<inspire_dls:SpatialDataSetIdentifier>
<inspire_common:Code>BDLJE</inspire_common:Code>
<inspire_common:Namespace>IGN</inspire_common:Namespace>

```
because this is already linked by <gmd:CI_OnlineResource> and MetadataURL.

**Maybe I am missing some utility of these identifiers… But as I see it this can be simplified.**
