### ISSUE TITLE
Part B - Remapping of Extended Capabilities - About Unique Resource Identifier (inspire_dls:SpatialDataSetIdentifier)

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#52]
From the [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224):

![image](https://user-images.githubusercontent.com/11427611/159578045-87315d0d-4f55-4e14-93fc-2468cf893be4.png)

![image](https://user-images.githubusercontent.com/11427611/159578067-4c35fce8-59c3-4491-8bba-7b305c60bed2.png)

So the metadata element [Unique resource identifier](https://inspire.ec.europa.eu/glossary/MetadataElement-UniqueResourceIdentifier) is not relevant for services.

This seems to be written wrongly in the TG Download and TG View, or am I missing anything here?

![image](https://user-images.githubusercontent.com/11427611/159578406-8f1a38e1-22d8-4603-876f-407676e55685.png)

![image](https://user-images.githubusercontent.com/11427611/159578666-cea2414d-e6df-4974-890a-988f272d0549.png)

![image](https://user-images.githubusercontent.com/11427611/159578685-9bd19407-e40d-48c7-b654-2b2c197d2985.png)

As for [INSPIRE Spatial data set identifier](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md#39-inspire-spatial-data-set-identifier-), this means, as far as I can see, that that section can be removed completely. You could argue that inspire_dls:SpatialDataSetIdentifier is the mapping of “Coupled Resource”, but we have the Coupled Resource already via `wfs:MetadataURL`.

**Comment by MarieLambois** [comment]
I think that indeed the idea was to have the id of the coupled ressource. In any case I agree that this is achieved by the `MetadataUrl` element.

**Comment by idevisser** [comment]
I agree  that section can be removed as Unique resource identifier is not relevant for services and  that this is achieved by the MetadataUrl element.

**Comment by jescriu** [comment]
Dear @heidivanparys, @AntoRot, @MarieLambois, @idevisser,

Thank you for your analysis.

Regarding the [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224), and your comment:

> So the metadata element [Unique resource identifier](https://inspire.ec.europa.eu/glossary/MetadataElement-UniqueResourceIdentifier) is not relevant for services.

Indeed the IR on metadata is not including the '[Unique resource identifier](https://inspire.ec.europa.eu/glossary/MetadataElement-UniqueResourceIdentifier)' as a required metadata element to be applied to *services*.

In my view: 

- In Table 19 'Mapping INSPIRE Metadata elements to ISO 19142 WFS' of the TG for Download services, the pair `inspire_dls:SpatialDataSetIdentifier/inspire_common:Code` + `inspire_dls:SpatialDataSetIdentifier/inspire_common:Namespace` is clearly re-using the 'Unique resource identifier' of the *Spatial Data Set* (i.e. not referring to the *service*) - If I am not wrong this was used in the current INSPIRE Geoportal to establish a virtual link to the data set being served through the WFS service (via the INSPIRE Identifier of the spatial data set), probably for purposes of quality checking in the infrastructure (i.e. assure correct data-service linking comparing the service Capabilities and the data set metadata) - At the end, the information regarded to the spatial data set can be obtained through the Coupled resource (`wfs:MetadataURL`).

- In Table 4 of the TG on View services (regarding WMS), the pair `wms:Identifier` + `wms:AuthorityURL` (present within each `wms:Layer`) is also referring to referring to the 'Unique resource identifier' of the *Spatial Data Set* - Again, similar case than the one explained above. In this case, the information regarded to the spatial data set can be obtained through the Coupled resource (`wms:MetadataURL`).

- I have not revised the case of Table 13 of the TG on View services (regarding WMTS), but I suppose that something similar applies to the element `ows:Identifier`.

In summary, **I agree with all of you that in the [consolidated proposal proposal for the Remapping of Extended Capabilities (Part B)](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md), the section on the 'Unique Resource Identifier' (Data set identifier in the data set metadata) can be omitted** - because the `MetadataURL` would be enough for data-service linking purposes. **However, I think some explanatory note based on what is explained above would be more than helpful**.

Having this said, probably some functionalities of the current INSPIRE Geoportal backend would be affected (those regarding the mentioned quality checking). However, since we are in the process to dismiss it and replace it with the new GeoNetwork backend, we will assure that no functionalities are compromised in the revamped INSPIRE Geoportal.

**Comment by heidivanparys** [comment]
> **However, I think some explanatory note based on what is explained above would be more than helpful**.

I think it would also be useful if some experts that were involved in the drafting of the original TGs could give their view on why the Unique Resource Identifier element was included. Was it a mistake? Was it a deliberate choice to include this, and in a way have the Coupled Resource represented twice? If the latter, why exactly?

**Comment by jescriu** [comment]
Thank @idevisser - Slight amendments:
The IR on metadata is not including the Unique resource identifier as a required metadata element to be applied to services.
The TG for Download and View services **are** using the 'Unique resource identifier' **to refer** to the Spatial Data Set. In the current INSPIRE Geoportal this used**,** in some cases, to establish a link between data and service **for quality control purposes**. The Coupled resource would be enough for data-service linking purposes, as is used **e.g.** in case of a WMS in the current INSPIRE Geoportal.

**Comment by jescriu** [comment]
Please, @heidivanparys, @AntoRot, @MarieLambois and @idevisser,
Let me know if [this final proposal](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/52#issuecomment-1176350451) is OK to close this issue.

**Comment by heidivanparys** [comment]
One proposal for improvement:

The IR on metadata is not including the Unique resource identifier as a required metadata element to be applied to services.
The TG for Download and View services **specify a WxS/Atom metadata element that contains the Unique Resource Identifier of** the Spatial Data Set. In the current INSPIRE Geoportal this is used, in some cases, to establish a link between data and service for quality control purposes. The Coupled resource would be enough for data-service linking purposes, as is used e.g. in case of a WMS in the current INSPIRE Geoportal.

**Comment by jescriu** [comment]
**Meeting on 2022-09-23**
Agree on the note from Heidi
