### ISSUE TITLE
contributing to Evidence of implementation & support

### ISSUE THREAD

**Issue by jsaligoe** [INSPIRE-MIF/gp-data-service-linking-simplification#57]
Dear Team, We are interested in: reviewing the most recent set of recommendations herein for the service linking simplification in the context of our current SW/SaaS deployments; commenting on (if any) discrepancies of this approach towards the goal "proven to be implementable by de facto standard web applications" with our existing out-of-the-box SW/SaaS; and, contributing to the [Evidence of Implementation and Support](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/good-practice/good-practice-fiche.md#evidence-of-implementation--support). We have established a [demonstration hub](https://arcgis-inspire-esri.opendata.arcgis.com/) for this purpose and have implemented several demonstration datasets following both the [INSPIRE Alternative Encoding](https://github.com/INSPIRE-MIF/2017.2) guidance, and early proposed approaches herein.

I've explored this repo and followed discussions. As there are several docs and ongoing threads, to make sure we are evaluating against the most current proposal, can someone provide a link in this thread to the proper resource/most current proposal?

Also, we would welcome opportunities to discuss further and participate in future meetings, as appropriate.  

Best regards, Jill Saligoe-Simmel, Esri Product Manager

**Comment by jescriu** [comment]
Dear @jsaligoe,
Excuse me for the late answer, but the Action 2.3.2 team was still working on finishing the specification. 

The current work is based in two parts:
- [Part A: Data-service linking simplification approach](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md).
- [Part B: Remapping of Extended Capabilities](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/Part-B-team/Consolidated-proposal-Part-B.md). 

Despite slight changes could be still applied to both parts, they will be merged in a final specification during this week, so that Part B will be included within the main part (substituting current Annex B in Part A) - I will post you when this merge is done.

On 21st November it is foreseen the Outreach webinar for this good practice candidate, which you are kindly invited to attend - More news on this event possibly tomorrow.

Best,
Jordi
