### ISSUE TITLE
endpoint versus accesspoint

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/gp-data-service-linking-simplification#7]
We need a clear definition of _accesspoint_ and _endpoint_.

- service-md: AP or EP
- service getCap: AP or EP
- getMap/getFeature: EP?
- AtomFeed: AP or EP
- datasetFeed: AP or EP
- DL-Link: EP?

Erik

**Comment by idevisser** [comment]
As a start point we have to use the definitions as defined in
https://inspire.ec.europa.eu/documents/commission-regulation-eu-no-13122014-10-december-2014-amending-regulation-eu-no-10892010-0

31. “end point” means the internet address used to directly call an operation provided by a spatial data service, 
32. “access point” means an internet address containing a detailed description of a spatial data service, including a list of end points to allow its execution,

With this in mind I would say

service-md: AP
service getCap: AP
getMap/getFeature: EP

I think we have to discuss the Atom

**Comment by oberseri** [comment]
I fear that the _getCap_ is not so clear as it is an _operation, that can be called_  (EP) AND _contains a detailed description_ (AP);
I know that there are different views on that; unfortunately the wording is often unclear (e.g. TG Metadata; Recommendation 1.9 and 3.5: - a service metadata (capabilities) document ...);

also AtomFeed/DatasetFeed are unclear as you said

**Comment by heidivanparys** [comment]
I tried to create an overview of some of the main concepts regarding services and some of the relations between them in the following diagram:

![image](https://user-images.githubusercontent.com/11427611/117647207-f80be900-b18c-11eb-9687-fccb2e3f6e1f.png)

So, according to what I found on web services, and services generally, a service access point - more commonly called a service entry point - _is (always) a kind of_ service endpoint. It is the endpoint where a client starts to use a service.

I guess the term "access point" comes from the UDDI specification, see also http://www.uddi.org/pubs/uddi-v3.0.2-20041019.htm#_Toc85908385. The term "endpoint" is widely used, for older and newer kinds of web services. Often, service endpoint address is used as a synonym for service endpoint (as e.g. in the IR), but although of course related (see diagram), those are two different things.

For a WFS, WMS, etc.:

- The entry point is the GetCapabilities endpoint (a web search on the following terms will confirm this: getcapabilities "entry point" ogc). The GetCapabilities endpoint provides the service description, containing the description of all the service endpoints (see also diagram).
- GetFeature, GetMap, etc. are endpoints.

For a service implementing one of the recent OGC API standards, the entry point is the landing page endpoint (see e.g. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#core-overview).

For a download service implemented with Atom, the entry point of the service would be the download service feed (the top-level feed).

![image](https://user-images.githubusercontent.com/11427611/117649558-f394ff80-b18f-11eb-849c-9a15e3b89845.png)

**Comment by dartasensi** [comment]
While reviewing all the comments and proposal received, I was thinking if we could _give up_ on the use of the `function` element, or any other elements available under `<gmd:CI_OnlineResource>`, to describe this kind of information about the URL.

To be clear: the definition for an endpoint (described at least as _Download/View Service_) will rely only on the human/software capability to discriminate (and rebuild) the defined URL.

For instance, all of the following ResourceLocator URLs can be seen and considered equivalent, if properly expressed through all the agreed elements (`protocolValue`, `applicationProfile`, etc) required by the Simplification.
- `<gmd:URL>http://.../ogc?request=GetCapabilities&amp;service={{WFS/WCS/WMS}}&[...]</gmd:URL>` or
- `<gmd:URL>http://.../ogc?request=GetMap&amp;service={{WFS/WCS/WMS}}&[...]</gmd:URL>` or
- `<gmd:URL>http://.../ogc?service={{WFS/WCS/WMS}}</gmd:URL>` or
- `<gmd:URL>http://.../ogc?</gmd:URL>` or
- `<gmd:URL>http://.../ogc</gmd:URL>`

Moving the focus on the more technical side (machine2machine interaction), on each of the aforementioned URLs of OGC services the software will look for a `GetCapabilities` request, and it should be able to deconstruct the URL and identify/substitute/integrate the parameters, in order to fulfill the API requirements of that OGC specification.
For an ATOM service, I found it quite impossible only from the URL alone, so it will be only discovered from its response (ie. `<atom:feed>` content instead of `wfs:GetCapabilities`). But at this point, a natural evolution of INSPIRE would be the deprecation of the support for ATOM.

I'm eager to receive your feedback/opinion about this.

KR,
Davide

**Comment by idevisser** [comment]
@dartasensi ,
You are right that it is possible to deconstruct the GetCapabilities from the URL. But in our opinion it is not desirable to have an URL not providing directly access, because the metadata is also harvested  and used in other applications.  The users (and maintainers) of other applications, are not always aware that a service URL should be requested. So they think it's a dead URL. This leads in the Netherlands to questions in the parliament.....(and a lot of work at my side) We now require that the URL is presented in such a way that it always gives a result immediately, without being queried.

And with having in mind that the metadata is also used in other systems, we should provide standardized and recognizable URL's. I think @heidivanparys did a very good exersise on what an accesspoint and endpoint is.


















































 It must not return an HTTP 0, 400 or 5XX message

**Comment by MarieLambois** [comment]
Discussed 2022-111-04: There are legal definition of those terms so issue can be closed.
