### ISSUE TITLE
Scenary 2: Avoiding Service Metadata files and use <inspire_common:Conformity>

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/gp-data-service-linking-simplification#9]
Hello, 

Last meeting we were talking about avoiding service metadata files for Network Services. 
We (the National Centre of Geographical Information - CNIG) agree on that, **applying the scenario 2** described in the document [TG_ViewServices_v3.11.pdf](https://inspire.ec.europa.eu/documents/Network_Services/TechnicalGuidance_ViewServices_v3.11.pdf). 

In our opinion the <inspire_vs:ExtendedCapabilities> is useful and, as you can see in the [TG_ViewServices_v3.11.pdf](https://inspire.ec.europa.eu/documents/Network_Services/TechnicalGuidance_ViewServices_v3.11.pdf), we can express the conformity with Regulation (EU) No 976/2009 using the element  **<inspire_common:Conformity>** within the <inspire_vs:ExtendedCapabilities> and c**alculate the NSi4-indicators** . The idea of using the element **<gmd:applicationProfile>** ( within the dataset metadata file) to express the conformity with the Regulation is not very precise and it implies some new unnecessary changes in the dataset metadata files.

**Comment by dartasensi** [comment]
Dear @LauraAlemany 

from my point of view, your suggestion is perfectly fine.
We agree that, at the moment, the current expression of the conformity in the `ExtendedCapabilities` is the perfect place and we should keep that.
On the other side, we should also re-evaluate and try to reduce the amount of required information in the `ExtendedCapabilities`, since it seems that many NCP indicates this commitment as difficult to do for different reasons (eg. lack of sw support for some services and impossibility to move to a different sw implementation) 

More about that, please have a look here #13, especially on the _Conformity declaration_ and _ExtendedCapabilities_ paragraphs and why we should keep it: #13

**Comment by MarieLambois** [comment]
Extended capabilities will still be an acceptable scenraio. Issue can be closed.
